source = ./apps/browsers.conf
source = ./apps/jetbrains.conf
source = ./apps/qemu.conf
source = ./apps/steam.conf
source = ./apps/system.conf
source = ./apps/telegram.conf
source = ./apps/terminals.conf
